inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/**/*"
    - "config/**/*"
    - "vendor/**/*"